### ISSUE TITLE
Firebase

### ISSUE THREAD

**Issue by kwadwo-ampadu** [Ali-Amin/shopx#5]
Can we know how your data from the Firebase Cloud Firestore is structured

**Comment by Ali-Amin** [comment]
Sure thing, There are 2 collections `categories` and `products`, see the screenshots below for details. 
I will add them to the README too in case anyone needs to take a look, if you have any other questions/requests feel free to ask.

## Categories
![CAT](https://user-images.githubusercontent.com/41022464/63609186-e9575a00-c5d6-11e9-805b-e4f7df9ffe23.PNG)
###
## Products
![PROD](https://user-images.githubusercontent.com/41022464/63609190-ea888700-c5d6-11e9-90e5-bf455d05f056.PNG)

**Comment by kwadwo-ampadu** [comment]
Thank you
